#!/bin/bash
cp implementation/system.bit ../bit_files/rpoco8_testbench_v11_2011_Dec_20_1342.bit
./mkbof -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
chmod +x implementation/system.bof
cp implementation/system.bof ../bit_files/rpoco8_testbench_v11_2011_Dec_20_1342.bof
